cursor_trail                1
window_padding_width        25
font_size 19
include themes/noctalia.conf
shell zsh
font_family Iosevka Custom
hide_window_decorations yes
tab_bar_style hidden
confirm_os_window_close 0
map ctrl+shift+t launch --cwd=current --type=tab
