color0 #353433
color1 #e17300
color2 #ffc072
color3 #ffe0c6
color4 #b9ab66
color5 #ed9562
color6 #f4c16e
color7 #ecd4c1
color8 #b29f91
color9 #ff8a22
color10 #ffd6a8
color11 #fff2e8
color12 #d7be92
color13 #fcad7e
color14 #ffd498
color15 #ffffff

cursor                #e2c0a5
cursor_text_color     #130d09
background            #130d09
foreground            #f6e2d3
selection_foreground  #baa89a
selection_background  #2f241a
active_border_color   #f1bc8f
inactive_border_color #2f241a
url_color             #f1bc8f

active_tab_foreground   #5b3816
active_tab_background   #f1bc8f
inactive_tab_foreground #baa89a
inactive_tab_background #2f241a
cursor_trail_color      #baa89a
