color0 #9f9a95
color1 #8d5300
color2 #9e7b00
color3 #9b6400
color4 #b08118
color5 #a05800
color6 #898228
color7 #27211d
color8 #100f0e
color9 #ae6700
color10 #c49b12
color11 #bc7e1f
color12 #d7a33b
color13 #c66e00
color14 #aba345
color15 #2e2723

cursor                #675d4e
cursor_text_color     #fff8f3
background            #fff8f3
foreground            #1d1b19
selection_foreground  #4d463c
selection_background  #ece1d4
active_border_color   #6c593b
inactive_border_color #ece1d4
url_color             #6c593b

active_tab_foreground   #ffffff
active_tab_background   #6c593b
inactive_tab_foreground #4d463c
inactive_tab_background #ece1d4
cursor_trail_color      #4d463c
