monitor = ,preferred,auto,0.7
decoration {
    rounding = 10

    blur {
        enabled = true
        size = 20
        passes = 3
        new_optimizations = true
    }

    active_opacity = 0.5
    inactive_opacity = 0.5
}
exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
# Workspaces
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true

# Switch workspaces
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

# Move active window to workspace
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5


# floating window
bind = $mainMod, V, togglefloating
bind = $mainMod SHIFT, right, resizeactive, 50 0
bind = $mainMod SHIFT, left, resizeactive, -50 0
bind = $mainMod SHIFT, up, resizeactive, 0 -50
bind = $mainMod SHIFT, down, resizeactive, 0 50

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod, C, centerwindow
