color0 #353433
color1 #e66f00
color2 #ffc079
color3 #ffe0c8
color4 #b9ab66
color5 #ee9467
color6 #f7bf6f
color7 #ecd4c1
color8 #b29f92
color9 #ff8931
color10 #ffd6ac
color11 #fff2e9
color12 #d9bd92
color13 #fdac82
color14 #ffd49d
color15 #ffffff

cursor                #e4c0a6
cursor_text_color     #130d09
background            #130d09
foreground            #f7e1d4
selection_foreground  #bba79b
selection_background  #2f231b
active_border_color   #f3bb91
inactive_border_color #2f231b
url_color             #f3bb91

active_tab_foreground   #5d3718
active_tab_background   #f3bb91
inactive_tab_foreground #bba79b
inactive_tab_background #2f231b
cursor_trail_color      #bba79b
