format = """
$directory$git_branch$git_status$cmd_duration
$character"""
[directory]
read_only = ''
[cmd_duration]
format = "[$duration]($style)"


[package]
disabled = true

[nodejs]
disabled = true
[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'



